# Generated by Django 5.1.6 on 2025-04-21 04:10

import datetime
import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieListPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('date_label', models.CharField(default='Today', max_length=50)),
                ('date_value', models.DateField(default=datetime.date.today)),
                ('available_dates', models.JSONField(blank=True, default=list)),
                ('movies', wagtail.fields.StreamField([('movie', 9)], blank=True, block_lookup={0: ('wagtail.blocks.DateBlock', (), {'label': 'Start Date'}), 1: ('wagtail.blocks.DateBlock', (), {'label': 'End Date'}), 2: ('wagtail.blocks.CharBlock', (), {'label': 'Category'}), 3: ('wagtail.blocks.CharBlock', (), {'label': 'Title'}), 4: ('wagtail.blocks.CharBlock', (), {'label': 'Director'}), 5: ('wagtail.blocks.CharBlock', (), {'label': 'Showtime'}), 6: ('wagtail.blocks.ListBlock', (5,), {}), 7: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 8: ('wagtail.blocks.CharBlock', (), {'label': 'Link (optional)', 'required': False}), 9: ('wagtail.blocks.StructBlock', [[('start_date', 0), ('end_date', 1), ('category', 2), ('title', 3), ('director', 4), ('times', 6), ('image', 7), ('link', 8)]], {})})),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
