# Generated by Django 5.1.6 on 2025-04-21 04:10

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='NightFuryPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('excerpt', models.TextField(blank=True, null=True)),
                ('author', models.CharField(blank=True, max_length=100, null=True)),
                ('publication_date', models.DateField(blank=True, null=True)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('tags', models.JSONField(blank=True, default=list, null=True)),
                ('body', wagtail.fields.RichTextField(blank=True, null=True)),
                ('additional_info', wagtail.fields.StreamField([('heading', 0), ('paragraph', 1)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'full title'}), 1: ('wagtail.blocks.RichTextBlock', (), {})}, null=True)),
                ('gallery', wagtail.fields.StreamField([('image_list', 1)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 1: ('wagtail.blocks.ListBlock', (0,), {})}, null=True)),
                ('testimonials', wagtail.fields.StreamField([('testimonial', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {}), 1: ('wagtail.blocks.RichTextBlock', (), {}), 2: ('wagtail.blocks.StructBlock', [[('author', 0), ('quote', 1)]], {})}, null=True)),
                ('call_to_action', wagtail.fields.StreamField([('cta', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {}), 1: ('wagtail.blocks.URLBlock', (), {}), 2: ('wagtail.blocks.StructBlock', [[('cta_text', 0), ('cta_link', 1)]], {})}, null=True)),
                ('related_articles', wagtail.fields.StreamField([('related', 3)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {}), 1: ('wagtail.blocks.URLBlock', (), {}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 3: ('wagtail.blocks.StructBlock', [[('title', 0), ('link', 1), ('image', 2)]], {})}, null=True)),
                ('feature_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'NightFuryPage',
                'verbose_name_plural': 'NightFuryPages',
                'default_related_name': 'custom_NightFury_pages',
            },
            bases=('wagtailcore.page',),
        ),
    ]
