# Generated by Django 5.1.6 on 2025-03-01 22:50

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.CreateModel(
            name='NormalPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('components', wagtail.fields.StreamField([('hero_section', 7), ('content_block', 29)], blank=True, block_lookup={0: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('hero', 'Hero Section'), ('carousel', 'Carousel'), ('jumbotron', 'Jumbotron')], 'help_text': 'Select the type of hero section'}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': 'Main headline', 'required': True}), 2: ('wagtail.blocks.TextBlock', (), {'help_text': 'Subtext below the title', 'required': False}), 3: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Background image', 'required': False}), 4: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'help_text': 'Upload a background video', 'required': False}), 5: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 6: ('wagtail.blocks.ListBlock', (5,), {'help_text': 'Add multiple images for the carousel', 'required': False}), 7: ('wagtail.blocks.StructBlock', [[('hero_type', 0), ('title', 1), ('subtitle', 2), ('background_image', 3), ('background_video', 4), ('carousel_images', 6)]], {}), 8: ('wagtail.blocks.CharBlock', (), {'help_text': 'Section Title', 'required': True}), 9: ('wagtail.blocks.CharBlock', (), {'help_text': 'Accordion Item Title', 'required': True}), 10: ('wagtail.blocks.RichTextBlock', (), {'help_text': 'Accordion Content', 'required': True}), 11: ('wagtail.blocks.StructBlock', [[('title', 9), ('content', 10)]], {}), 12: ('wagtail.blocks.ListBlock', (11,), {'help_text': 'Add multiple accordion items'}), 13: ('wagtail.blocks.StructBlock', [[('items', 12)]], {}), 14: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Optional card image', 'required': False}), 15: ('wagtail.blocks.CharBlock', (), {'help_text': 'Card Title', 'required': True}), 16: ('wagtail.blocks.TextBlock', (), {'help_text': 'Card Description', 'required': True}), 17: ('wagtail.blocks.StructBlock', [[('image', 14), ('title', 15), ('description', 16)]], {}), 18: ('wagtail.blocks.CharBlock', (), {'help_text': 'Tab Title', 'required': True}), 19: ('wagtail.blocks.RichTextBlock', (), {'help_text': 'Tab Content', 'required': True}), 20: ('wagtail.blocks.StructBlock', [[('tab_title', 18), ('tab_content', 19)]], {}), 21: ('wagtail.blocks.DateBlock', (), {'help_text': 'Event Date', 'required': True}), 22: ('wagtail.blocks.CharBlock', (), {'help_text': 'Event Title', 'required': True}), 23: ('wagtail.blocks.TextBlock', (), {'help_text': 'Event Description', 'required': True}), 24: ('wagtail.blocks.StructBlock', [[('event_date', 21), ('event_title', 22), ('event_description', 23)]], {}), 25: ('wagtail.blocks.ListBlock', (24,), {'help_text': 'Add timeline events'}), 26: ('wagtail.blocks.StructBlock', [[('timeline_items', 25)]], {}), 27: ('wagtail.blocks.StreamBlock', [[('accordion', 13), ('card', 17), ('tab', 20), ('timeline', 26)]], {'required': False}), 28: ('wagtail.blocks.ListBlock', (27,), {'help_text': 'Add content display components'}), 29: ('wagtail.blocks.StructBlock', [[('title', 8), ('content_display_components', 28)]], {})})),
            ],
            options={
                'verbose_name': 'Normal Page',
            },
            bases=('wagtailcore.page',),
        ),
    ]
