# Generated by Django 5.1.6 on 2025-04-21 04:10

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0027_image_description'),
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='normalpage',
            name='body',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='normalpage',
            name='heroSectionImage',
            field=models.FileField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='normalpage',
            name='heroSectionVideo',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
        migrations.AddField(
            model_name='normalpage',
            name='heroTitle',
            field=models.TextField(blank=True, help_text='Description of Our Film Festival'),
        ),
        migrations.AddField(
            model_name='normalpage',
            name='heroType',
            field=models.CharField(choices=[('Image', 'Use background image'), ('Video', 'Use background video'), ('Carousel', 'Carousel')], default='option1', max_length=20),
        ),
        migrations.AlterField(
            model_name='normalpage',
            name='components',
            field=wagtail.fields.StreamField([('content_block', 21)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Section Title', 'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': 'Accordion Item Title', 'required': True}), 2: ('wagtail.blocks.RichTextBlock', (), {'help_text': 'Accordion Content', 'required': True}), 3: ('wagtail.blocks.StructBlock', [[('title', 1), ('content', 2)]], {}), 4: ('wagtail.blocks.ListBlock', (3,), {'help_text': 'Add multiple accordion items'}), 5: ('wagtail.blocks.StructBlock', [[('items', 4)]], {}), 6: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Optional card image', 'required': False}), 7: ('wagtail.blocks.CharBlock', (), {'help_text': 'Card Title', 'required': True}), 8: ('wagtail.blocks.TextBlock', (), {'help_text': 'Card Description', 'required': True}), 9: ('wagtail.blocks.StructBlock', [[('image', 6), ('title', 7), ('description', 8)]], {}), 10: ('wagtail.blocks.CharBlock', (), {'help_text': 'Tab Title', 'required': True}), 11: ('wagtail.blocks.RichTextBlock', (), {'help_text': 'Tab Content', 'required': True}), 12: ('wagtail.blocks.StructBlock', [[('tab_title', 10), ('tab_content', 11)]], {}), 13: ('wagtail.blocks.DateBlock', (), {'help_text': 'Event Date', 'required': True}), 14: ('wagtail.blocks.CharBlock', (), {'help_text': 'Event Title', 'required': True}), 15: ('wagtail.blocks.TextBlock', (), {'help_text': 'Event Description', 'required': True}), 16: ('wagtail.blocks.StructBlock', [[('event_date', 13), ('event_title', 14), ('event_description', 15)]], {}), 17: ('wagtail.blocks.ListBlock', (16,), {'help_text': 'Add timeline events'}), 18: ('wagtail.blocks.StructBlock', [[('timeline_items', 17)]], {}), 19: ('wagtail.blocks.StreamBlock', [[('accordion', 5), ('card', 9), ('tab', 12), ('timeline', 18)]], {'required': False}), 20: ('wagtail.blocks.ListBlock', (19,), {'help_text': 'Add content display components'}), 21: ('wagtail.blocks.StructBlock', [[('title', 0), ('content_display_components', 20)]], {})}),
        ),
        migrations.CreateModel(
            name='CarouselImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='carousel_images', to='website.normalpage')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.image')),
            ],
        ),
    ]
