# Generated by Django 5.1.6 on 2025-04-21 04:10

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepage_body_homepage_herosectionvideo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='body',
        ),
        migrations.AddField(
            model_name='homepage',
            name='films',
            field=wagtail.fields.StreamField([('film', 3)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Film Title', 'required': True}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Optional card image', 'required': False}), 2: ('wagtail.blocks.CharBlock', (), {'default': 'https://www.', 'help_text': 'Redirect to: ', 'required': True}), 3: ('wagtail.blocks.StructBlock', [[('title', 0), ('image', 1), ('href', 2)]], {})}),
        ),
        migrations.AddField(
            model_name='homepage',
            name='heroText',
            field=models.CharField(default='Welcome to Los Angeles International Film Festival', help_text='Title of the Page', max_length=200),
        ),
    ]
