# Generated by Django 5.1.6 on 2025-04-21 04:10

import django.core.validators
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NightFuryNavSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', wagtail.fields.RichTextField(blank=True)),
                ('contact_email', models.TextField(blank=True, verbose_name='Email')),
                ('contact_phone', models.TextField(blank=True, help_text="Enter phone number in the format: '+999999999'.", max_length=25, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Phone Number')),
                ('instagram_url', models.URLField(blank=True, verbose_name='Instagram Home Page')),
                ('facebook_url', models.URLField(blank=True, verbose_name='Facebook Home Page')),
                ('youtube_url', models.URLField(blank=True, verbose_name='YouTube Home Page')),
                ('twitter_url', models.URLField(blank=True, verbose_name='Twitter Home Page')),
            ],
            options={
                'verbose_name': 'Navigation Settings',
            },
        ),
    ]
