# Generated by Django 5.1.6 on 2025-04-21 04:10

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilmPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('name', models.CharField(blank=True, help_text='Film Title', max_length=512)),
                ('description', wagtail.fields.RichTextField(blank=True, help_text='Film Description')),
                ('director', models.CharField(blank=True, help_text='Film Director', max_length=200)),
                ('released_year', models.PositiveIntegerField(default=2025, help_text='Released Date')),
                ('genres', models.CharField(blank=True, default='', help_text='Comma-separated genres (e.g. Sci-Fi, Thriller)', max_length=512)),
                ('photo', models.FileField(blank=True, null=True, upload_to='images/')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
