# Generated by Django 5.1.7 on 2025-03-29 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filmpage',
            name='director',
            field=models.CharField(blank=True, help_text='Film Director', max_length=200),
        ),
        migrations.AddField(
            model_name='filmpage',
            name='genres',
            field=models.CharField(blank=True, help_text='Comma-separated genres (e.g. Sci-Fi, Thriller)', max_length=512),
        ),
        migrations.AddField(
            model_name='filmpage',
            name='released_year',
            field=models.PositiveIntegerField(default=2025, help_text='Released Date'),
        ),
    ]
