# Generated by Django 5.1.7 on 2025-03-29 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0002_filmpage_director_filmpage_genres_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmpage',
            name='genres',
            field=models.CharField(blank=True, default='', help_text='Comma-separated genres (e.g. Sci-Fi, Thriller)', max_length=512),
        ),
    ]
